[package]
name = "codeclub-desktop"
version = "0.1.0"
description = "Codeclub desktop app"
authors = ["Codeclub"]
edition = "2024"

[lib]
name = "codeclub_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
tauri = { version = "2.9.5", features = ["unstable"] }
tauri-plugin-opener = "2.5.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
uiautomation = { version = "0.25", features = ["all"] }
windows = { version = "0.61", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "charset", "http2", "gzip", "brotli", "deflate", "json"] }
